# site settings
title: Association Étudiante de Démographie
subtitle: Université de Montréal
email: aedem.udem@gmail.com
description:
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: https://aedem-udem.github.io/
author:
street_address: 3150, rue Jean-Brillant, Montréal
city: Montréal
state: QC
zip_code: H3T 1N8
country: Canada
phone:

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub:
  GitLab:
  Google-Plus:
  Instagram:
  LinkedIn:
  Twitter: 
  Facebook:https://www.facebook.com/groups/4817708075
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
